"""create v2 work catalog core

Revision ID: 25ff14940d0d
Revises:
Create Date: 2026-09-02 19:12:13.354438
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "25ff14940d0d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "v2_assets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("detected_media_type", sa.String(length=255), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "state IN ('pending_inspection', 'ready', 'rejected')", name="asset_state"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sha256"),
    )
    op.create_table(
        "v2_change_events",
        sa.Column("sequence", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column("entity_revision", sa.Integer(), nullable=False),
        sa.Column("operation", sa.String(length=100), nullable=False),
        sa.Column("actor_id", sa.String(length=100), nullable=False),
        sa.Column("device_id", sa.String(length=200), nullable=True),
        sa.Column("request_id", sa.String(length=200), nullable=True),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("tombstone", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("sequence"),
    )
    op.create_table(
        "v2_contributors",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("display_name", sa.String(length=500), nullable=False),
        sa.Column("sort_name", sa.String(length=500), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "v2_idempotency_keys",
        sa.Column("actor_id", sa.String(length=100), nullable=False),
        sa.Column("scope", sa.String(length=300), nullable=False),
        sa.Column("key", sa.String(length=300), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("response_json", sa.JSON(), nullable=False),
        sa.Column("response_headers_json", sa.JSON(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("actor_id", "scope", "key"),
    )
    op.create_table(
        "v2_works",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("canonical_title", sa.String(length=500), nullable=False),
        sa.Column("language", sa.String(length=35), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("status IN ('draft', 'active', 'archived')", name="work_status"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("v2_works", schema=None) as batch_op:
        batch_op.create_index("v2_works_title_idx", ["canonical_title"], unique=False)

    op.create_table(
        "v2_arrangements",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("work_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("voicing", sa.String(length=100), nullable=True),
        sa.Column("key_signature", sa.String(length=100), nullable=True),
        sa.Column("based_on_id", sa.String(length=36), nullable=True),
        sa.Column("preferred_score_id", sa.String(length=36), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["based_on_id"], ["v2_arrangements.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["preferred_score_id"], ["v2_scores.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["work_id"], ["v2_works.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("v2_arrangements", schema=None) as batch_op:
        batch_op.create_index("v2_arrangements_work_idx", ["work_id"], unique=False)

    op.create_table(
        "v2_asset_locations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("asset_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("storage_key", sa.String(length=1000), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "state IN ('available', 'migrating', 'missing')", name="asset_location_state"
        ),
        sa.ForeignKeyConstraint(["asset_id"], ["v2_assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("asset_id", "provider", name="uq_v2_asset_provider"),
        sa.UniqueConstraint("provider", "storage_key", name="uq_v2_asset_location"),
    )
    op.create_table(
        "v2_asset_sources",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("asset_id", sa.String(length=36), nullable=False),
        sa.Column("original_filename", sa.String(length=1000), nullable=True),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("source_ref", sa.String(length=1000), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["v2_assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "v2_change_event_works",
        sa.Column("event_sequence", sa.Integer(), nullable=False),
        sa.Column("work_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_sequence"], ["v2_change_events.sequence"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["work_id"], ["v2_works.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("event_sequence", "work_id"),
    )
    with op.batch_alter_table("v2_change_event_works", schema=None) as batch_op:
        batch_op.create_index(
            "v2_change_event_works_work_idx", ["work_id", "event_sequence"], unique=False
        )

    op.create_table(
        "v2_upload_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("expected_sha256", sa.String(length=64), nullable=False),
        sa.Column("expected_size", sa.Integer(), nullable=False),
        sa.Column("media_type", sa.String(length=255), nullable=False),
        sa.Column("original_filename", sa.String(length=1000), nullable=True),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("source_ref", sa.String(length=1000), nullable=True),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("temporary_key", sa.String(length=1000), nullable=True),
        sa.Column("actual_sha256", sa.String(length=64), nullable=True),
        sa.Column("actual_size", sa.Integer(), nullable=True),
        sa.Column("completed_asset_id", sa.String(length=36), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "state IN ('created', 'uploaded', 'completed', 'failed', 'expired')",
            name="upload_session_state",
        ),
        sa.ForeignKeyConstraint(["completed_asset_id"], ["v2_assets.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "v2_work_aliases",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("work_id", sa.String(length=36), nullable=False),
        sa.Column("namespace", sa.String(length=100), nullable=False),
        sa.Column("external_id", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["work_id"], ["v2_works.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("namespace", "external_id", name="uq_v2_work_alias"),
    )
    with op.batch_alter_table("v2_work_aliases", schema=None) as batch_op:
        batch_op.create_index("v2_work_aliases_work_idx", ["work_id"], unique=False)

    op.create_table(
        "v2_work_credits",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("work_id", sa.String(length=36), nullable=False),
        sa.Column("contributor_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=100), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["contributor_id"], ["v2_contributors.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["work_id"], ["v2_works.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("work_id", "contributor_id", "role", name="uq_v2_work_credit"),
    )
    op.create_table(
        "v2_parts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("arrangement_id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("midi_channel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "midi_channel IS NULL OR (midi_channel >= 1 AND midi_channel <= 16)",
            name="part_midi_channel",
        ),
        sa.ForeignKeyConstraint(["arrangement_id"], ["v2_arrangements.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("arrangement_id", "code", name="uq_v2_part_code"),
    )
    op.create_table(
        "v2_renditions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("arrangement_id", sa.String(length=36), nullable=False),
        sa.Column("label", sa.String(length=500), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("ensemble", sa.String(length=500), nullable=True),
        sa.Column("recorded_at", sa.String(length=10), nullable=True),
        sa.Column("location", sa.String(length=500), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["arrangement_id"], ["v2_arrangements.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("v2_renditions", schema=None) as batch_op:
        batch_op.create_index("v2_renditions_arrangement_idx", ["arrangement_id"], unique=False)

    op.create_table(
        "v2_scores",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("arrangement_id", sa.String(length=36), nullable=False),
        sa.Column("label", sa.String(length=500), nullable=False),
        sa.Column("origin", sa.String(length=50), nullable=False),
        sa.Column("derived_from_revision_id", sa.String(length=36), nullable=True),
        sa.Column("head_revision_id", sa.String(length=36), nullable=True),
        sa.Column("published_revision_id", sa.String(length=36), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "origin IN ('ocr', 'midi_transcription', 'manual', 'external_import')",
            name="score_origin",
        ),
        sa.ForeignKeyConstraint(["arrangement_id"], ["v2_arrangements.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["derived_from_revision_id"], ["v2_score_revisions.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["head_revision_id"], ["v2_score_revisions.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["published_revision_id"], ["v2_score_revisions.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("v2_scores", schema=None) as batch_op:
        batch_op.create_index("v2_scores_arrangement_idx", ["arrangement_id"], unique=False)

    op.create_table(
        "v2_rendition_assets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("rendition_id", sa.String(length=36), nullable=False),
        sa.Column("asset_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("part_id", sa.String(length=36), nullable=True),
        sa.Column("codec_profile", sa.String(length=100), nullable=True),
        sa.CheckConstraint(
            "(role = 'stem' AND part_id IS NOT NULL) OR (role <> 'stem' AND part_id IS NULL)",
            name="rendition_asset_part_role",
        ),
        sa.ForeignKeyConstraint(["asset_id"], ["v2_assets.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["part_id"], ["v2_parts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["rendition_id"], ["v2_renditions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "rendition_id", "asset_id", "role", "part_id", name="uq_v2_rendition_asset"
        ),
    )
    op.create_table(
        "v2_rendition_credits",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("rendition_id", sa.String(length=36), nullable=False),
        sa.Column("contributor_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=100), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["contributor_id"], ["v2_contributors.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["rendition_id"], ["v2_renditions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "rendition_id", "contributor_id", "role", name="uq_v2_rendition_credit"
        ),
    )
    op.create_table(
        "v2_score_revisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("score_id", sa.String(length=36), nullable=False),
        sa.Column("revision_no", sa.Integer(), nullable=False),
        sa.Column("based_on_revision_id", sa.String(length=36), nullable=True),
        sa.Column("edit_message", sa.Text(), nullable=True),
        sa.Column("editor_id", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["based_on_revision_id"], ["v2_score_revisions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["score_id"], ["v2_scores.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("score_id", "revision_no", name="uq_v2_score_revision_no"),
    )
    with op.batch_alter_table("v2_score_revisions", schema=None) as batch_op:
        batch_op.create_index("v2_score_revisions_score_idx", ["score_id"], unique=False)

    op.create_table(
        "v2_score_revision_assets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("score_revision_id", sa.String(length=36), nullable=False),
        sa.Column("asset_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["v2_assets.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["score_revision_id"], ["v2_score_revisions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "score_revision_id", "asset_id", "role", name="uq_v2_score_revision_asset"
        ),
    )
    with op.batch_alter_table("v2_score_revision_assets", schema=None) as batch_op:
        batch_op.create_index(
            "uq_v2_score_primary_musicxml",
            ["score_revision_id"],
            unique=True,
            sqlite_where=sa.text("role = 'primary_musicxml'"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("v2_score_revision_assets", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_v2_score_primary_musicxml", sqlite_where=sa.text("role = 'primary_musicxml'")
        )

    op.drop_table("v2_score_revision_assets")
    with op.batch_alter_table("v2_score_revisions", schema=None) as batch_op:
        batch_op.drop_index("v2_score_revisions_score_idx")

    op.drop_table("v2_score_revisions")
    op.drop_table("v2_rendition_credits")
    op.drop_table("v2_rendition_assets")
    with op.batch_alter_table("v2_scores", schema=None) as batch_op:
        batch_op.drop_index("v2_scores_arrangement_idx")

    op.drop_table("v2_scores")
    with op.batch_alter_table("v2_renditions", schema=None) as batch_op:
        batch_op.drop_index("v2_renditions_arrangement_idx")

    op.drop_table("v2_renditions")
    op.drop_table("v2_parts")
    op.drop_table("v2_work_credits")
    with op.batch_alter_table("v2_work_aliases", schema=None) as batch_op:
        batch_op.drop_index("v2_work_aliases_work_idx")

    op.drop_table("v2_work_aliases")
    op.drop_table("v2_upload_sessions")
    with op.batch_alter_table("v2_change_event_works", schema=None) as batch_op:
        batch_op.drop_index("v2_change_event_works_work_idx")

    op.drop_table("v2_change_event_works")
    op.drop_table("v2_asset_sources")
    op.drop_table("v2_asset_locations")
    with op.batch_alter_table("v2_arrangements", schema=None) as batch_op:
        batch_op.drop_index("v2_arrangements_work_idx")

    op.drop_table("v2_arrangements")
    with op.batch_alter_table("v2_works", schema=None) as batch_op:
        batch_op.drop_index("v2_works_title_idx")

    op.drop_table("v2_works")
    op.drop_table("v2_idempotency_keys")
    op.drop_table("v2_contributors")
    op.drop_table("v2_change_events")
    op.drop_table("v2_assets")
    # ### end Alembic commands ###
